version: "3.9"
services:
  web:
    image: planes/api-serv
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - GOOGLE_CLIENT_ID
      - SERVER_PORT=8080
      - CONNECTION_STRING=user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=postgres port=5432 dbname=${POSTGRES_DB}
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "~/docker-dirs/planes/postgres:/var/lib/postgresql/data"